In [3]:
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('train.csv')

In [52]:
df.describe()

AccountAge  MonthlyCharges   TotalCharges  SubscriptionType  \
count  243787.000000   243787.000000  243787.000000     243787.000000   
mean       60.083758       12.490695     750.741017          1.004524   
std        34.285143        4.327615     523.073273          0.817019   
min         1.000000        4.990062       4.991154          0.000000   
25%        30.000000        8.738543     329.147027          0.000000   
50%        60.000000       12.495555     649.878487          1.000000   
75%        90.000000       16.238160    1089.317362          2.000000   
max       119.000000       19.989957    2378.723844          2.000000   

       PaymentMethod  PaperlessBilling    ContentType  MultiDeviceAccess  \
count  243787.000000     243787.000000  243787.000000      243787.000000   
mean        1.501069          0.499645       0.997572           0.499420   
std         1.116775          0.500001       0.817392           0.500001   
min         0.000000          0.000000       0.000000           0.000000   
25%         1.000000          0.000000       0.000000           0.000000   
50%         2.000000          0.000000       1.000000           0.000000   
75%         2.000000          1.000000       2.000000           1.000000   
max         3.000000          1.000000       2.000000           1.000000   

       DeviceRegistered  ViewingHoursPerWeek  AverageViewingDuration  \
count     243787.000000        243787.000000           243787.000000   
mean           1.497972            20.502179               92.264061   
std            1.116579            11.243753               50.505243   
min            0.000000             1.000065                5.000547   
25%            1.000000            10.763953               48.382395   
50%            1.000000            20.523116               92.249992   
75%            2.000000            30.219396              135.908048   
max            3.000000            39.999723              179.999275   

       ContentDownloadsPerMonth  GenrePreference     UserRating  \
count             243787.000000    243787.000000  243787.000000   
mean                  24.503513         2.006145       3.002713   
std                   14.421174         1.413408       1.155259   
min                    0.000000         0.000000       1.000007   
25%                   12.000000         1.000000       2.000853   
50%                   24.000000         2.000000       3.002261   
75%                   37.000000         3.000000       4.002157   
max                   49.000000         4.000000       4.999989   

       SupportTicketsPerMonth         Gender  WatchlistSize  ParentalControl  \
count           243787.000000  243787.000000  243787.000000    243787.000000   
mean                 4.504186       0.500150      12.018508         0.500786   
std                  2.872548       0.500001       7.193034         0.500000   
min                  0.000000       0.000000       0.000000         0.000000   
25%                  2.000000       0.000000       6.000000         0.000000   
50%                  4.000000       1.000000      12.000000         1.000000   
75%                  7.000000       1.000000      18.000000         1.000000   
max                  9.000000       1.000000      24.000000         1.000000   

       SubtitlesEnabled          Churn  
count     243787.000000  243787.000000  
mean           0.501175       0.181232  
std            0.500000       0.385211  
min            0.000000       0.000000  
25%            0.000000       0.000000  
50%            1.000000       0.000000  
75%            1.000000       0.000000  
max            1.000000       1.000000

In [9]:
df.dtypes

AccountAge                    int64
MonthlyCharges              float64
TotalCharges                float64
SubscriptionType              int64
PaymentMethod                object
PaperlessBilling             object
ContentType                  object
MultiDeviceAccess            object
DeviceRegistered             object
ViewingHoursPerWeek         float64
AverageViewingDuration      float64
ContentDownloadsPerMonth      int64
GenrePreference              object
UserRating                  float64
SupportTicketsPerMonth        int64
Gender                       object
WatchlistSize                 int64
ParentalControl              object
SubtitlesEnabled             object
CustomerID                   object
Churn                         int64
dtype: object

In [8]:
df['SubscriptionType'] = df.SubscriptionType.map({'Premium':0, 'Basic':1, 'Standard':2})


In [8]:
df['SubscriptionType'].unique()


array([0, 1, 2], dtype=int64)

In [10]:
df['PaymentMethod'] = df.PaymentMethod.map({'Mailed check':0, 'Credit card':1, 'Electronic check':2,'Bank transfer':3})


In [12]:
df['PaymentMethod'].unique()

array([0, 1, 2, 3], dtype=int64)

In [11]:
df['PaperlessBilling'] = df.PaperlessBilling.map({'No':0, 'Yes':1})

In [16]:
df['PaperlessBilling'].unique()

array([0, 1], dtype=int64)

In [12]:
df['ContentType'] = df.ContentType.map({'Both':0, 'Movies':1, 'TV Shows':2})

In [20]:
df['ContentType'].unique()

array([0, 1, 2], dtype=int64)

In [24]:
df['MultiDeviceAccess'].unique()

array([0, 1], dtype=int64)

In [13]:
df['MultiDeviceAccess'] = df.MultiDeviceAccess.map({'No':0, 'Yes':1})

In [28]:
df['DeviceRegistered'].unique()

array([0, 1, 2, 3], dtype=int64)

In [14]:
df['DeviceRegistered'] = df.DeviceRegistered.map({'Mobile':0, 'Tablet':1, 'Computer':2, 'TV':3})

In [15]:
df = df.drop('ContentDownloadsPerMonth', axis=1)

In [33]:
df['GenrePreference'].unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [16]:
df['GenrePreference'] = df.GenrePreference.map({'Sci-Fi':0, 'Action':1, 'Fantasy':2, 'Drama':3, 'Comedy':4})

In [55]:
df['UserRating'].unique()

array([2.17649751, 3.47863229, 4.23882362, ..., 4.01221731, 2.13578882,
       1.42889572])

In [56]:
df['SupportTicketsPerMonth'].unique()

array([4, 8, 6, 2, 9, 0, 1, 7, 3, 5], dtype=int64)

In [38]:
df['Gender'].unique()

array([0, 1], dtype=int64)

In [17]:
df['Gender'] = df.Gender.map({'Male':0, 'Female':1})

In [43]:
df['ParentalControl'].unique()

array([0, 1], dtype=int64)

In [18]:
df['ParentalControl'] = df.ParentalControl.map({'No':0, 'Yes':1})

In [47]:
df['SubtitlesEnabled'].unique()

array([0, 1], dtype=int64)

In [19]:
df['SubtitlesEnabled'] = df.SubtitlesEnabled.map({'No':0, 'Yes':1})

In [20]:

df = df.drop('CustomerID', axis=1)

In [51]:
k_neighbors = neighbors.KNeighborsClassifier()

In [175]:
data_x = df.drop([ 'Gender', 'MonthlyCharges', 'ContentType', 
'MultiDeviceAccess', 'DeviceRegistered',
 'ViewingHoursPerWeek'
 , 'AverageViewingDuration', 
'ContentDownloadsPerMonth', 
'GenrePreference', 'UserRating',
 'WatchlistSize'
, 'Churn'], axis='columns')
data_y = df.SubtitlesEnabled

In [130]:
df.describe()

AccountAge  MonthlyCharges   TotalCharges  SubscriptionType  \
count  243787.000000   243787.000000  243787.000000     243787.000000   
mean       60.083758       12.490695     750.741017          1.004524   
std        34.285143        4.327615     523.073273          0.817019   
min         1.000000        4.990062       4.991154          0.000000   
25%        30.000000        8.738543     329.147027          0.000000   
50%        60.000000       12.495555     649.878487          1.000000   
75%        90.000000       16.238160    1089.317362          2.000000   
max       119.000000       19.989957    2378.723844          2.000000   

       PaymentMethod  PaperlessBilling    ContentType  MultiDeviceAccess  \
count  243787.000000     243787.000000  243787.000000      243787.000000   
mean        1.501069          0.499645       0.997572           0.499420   
std         1.116775          0.500001       0.817392           0.500001   
min         0.000000          0.000000       0.000000           0.000000   
25%         1.000000          0.000000       0.000000           0.000000   
50%         2.000000          0.000000       1.000000           0.000000   
75%         2.000000          1.000000       2.000000           1.000000   
max         3.000000          1.000000       2.000000           1.000000   

       DeviceRegistered  ViewingHoursPerWeek  AverageViewingDuration  \
count     243787.000000        243787.000000           243787.000000   
mean           1.497972            20.502179               92.264061   
std            1.116579            11.243753               50.505243   
min            0.000000             1.000065                5.000547   
25%            1.000000            10.763953               48.382395   
50%            1.000000            20.523116               92.249992   
75%            2.000000            30.219396              135.908048   
max            3.000000            39.999723              179.999275   

       ContentDownloadsPerMonth  GenrePreference     UserRating  \
count             243787.000000    243787.000000  243787.000000   
mean                  24.503513         2.006145       3.002713   
std                   14.421174         1.413408       1.155259   
min                    0.000000         0.000000       1.000007   
25%                   12.000000         1.000000       2.000853   
50%                   24.000000         2.000000       3.002261   
75%                   37.000000         3.000000       4.002157   
max                   49.000000         4.000000       4.999989   

       SupportTicketsPerMonth         Gender  WatchlistSize  ParentalControl  \
count           243787.000000  243787.000000  243787.000000    243787.000000   
mean                 4.504186       0.500150      12.018508         0.500786   
std                  2.872548       0.500001       7.193034         0.500000   
min                  0.000000       0.000000       0.000000         0.000000   
25%                  2.000000       0.000000       6.000000         0.000000   
50%                  4.000000       1.000000      12.000000         1.000000   
75%                  7.000000       1.000000      18.000000         1.000000   
max                  9.000000       1.000000      24.000000         1.000000   

       SubtitlesEnabled          Churn  
count     243787.000000  243787.000000  
mean           0.501175       0.181232  
std            0.500000       0.385211  
min            0.000000       0.000000  
25%            0.000000       0.000000  
50%            1.000000       0.000000  
75%            1.000000       0.000000  
max            1.000000       1.000000

In [176]:
train_x, test_x, train_y, test_y = train_test_split(data_x, data_y, test_size=0.1)

In [177]:
k_neighbors.fit(train_x, train_y)

KNeighborsClassifier()

In [178]:
print(f'Score: {round(k_neighbors.score(test_x, test_y), 4) * 100}%')

Score: 66.94%


In [ ]:
userRating =2
genrepreference = 3
predicted = k_neighbors.predict([[userRating, genrepreference]])

In [ ]:
isGender = ['hombre','mujer']
generodepref = ['Sci-Fi', 'Action', 'Fantasy', 'Drama', 'Comedy']

In [ ]:
print(f'La persona con {userRating} de puntuacion y con su genero de preferencia {generodepref [genrepreference]} . Se ha determinado que es {isGender[predicted[0]]}')


In [198]:
df.dtypes

AccountAge                    int64
MonthlyCharges              float64
TotalCharges                float64
SubscriptionType              int64
PaymentMethod                 int64
PaperlessBilling              int64
ContentType                   int64
MultiDeviceAccess             int64
DeviceRegistered              int64
ViewingHoursPerWeek         float64
AverageViewingDuration      float64
ContentDownloadsPerMonth      int64
GenrePreference               int64
UserRating                  float64
SupportTicketsPerMonth        int64
Gender                        int64
WatchlistSize                 int64
ParentalControl               int64
SubtitlesEnabled              int64
Churn                         int64
dtype: object

### Random Forest

In [21]:
forest = RandomForestClassifier()


In [24]:
data_x_forest = df.drop(['AccountAge','MonthlyCharges','TotalCharges',
'SubscriptionType','PaymentMethod','PaperlessBilling',
'ContentType','MultiDeviceAccess','DeviceRegistered',
'ViewingHoursPerWeek','AverageViewingDuration',
'SupportTicketsPerMonth','Gender',
'WatchlistSize','ParentalControl','SubtitlesEnabled','Churn'], axis='columns')
data_y_forest = df.Gender

In [25]:
print (data_x_forest)

        GenrePreference  UserRating
0                     0    2.176498
1                     1    3.478632
2                     2    4.238824
3                     3    4.276013
4                     4    3.616170
...                 ...         ...
243782                0    3.697451
243783                4    1.449742
243784                1    4.012217
243785                2    2.135789
243786                1    1.428896

[243787 rows x 2 columns]


In [26]:
train_x_forest, test_x_forest, train_y_forest, test_y_forest = train_test_split(data_x_forest, data_y_forest, test_size=0.1)

In [27]:
forest.fit(data_x_forest, data_y_forest)

RandomForestClassifier()

In [28]:
print(f'El score del modelo es: {round(forest.score(data_x_forest, data_y_forest), 4) *100}%')

El score del modelo es: 99.87%


In [30]:
userRating =2
genrepreference = 3
predicted = forest.predict([[userRating, genrepreference]])

c:\Users\Pedro\Desktop\SemestresUni\2-2023\algoritmica\Tarea2\entornovirtual\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [38]:
isGender = ['hombre','mujer']
generodepref = ['Sci-Fi', 'Action', 'Fantasy', 'Drama', 'Comedy']


In [39]:
print(f'La persona con {userRating} de puntuacion y con su genero de preferencia {generodepref [genrepreference]} . Se ha determinado que es {isGender[predicted[0]]}')


La persona con 2 de puntuacion y con su genero de preferencia Drama . Se ha determinado que es mujer


### Decision Tree

In [40]:
decission_model = DecisionTreeClassifier()

In [51]:
data_x_tree = df.drop(['AccountAge','MonthlyCharges','TotalCharges',
'SubscriptionType','PaymentMethod','PaperlessBilling',
'ContentType','MultiDeviceAccess','DeviceRegistered',
'ViewingHoursPerWeek','AverageViewingDuration',
'SupportTicketsPerMonth','Gender',
'WatchlistSize','ParentalControl','SubtitlesEnabled','Churn'
        ], axis='columns')
data_y_tree = df.Gender

In [52]:
train_x_tree, test_x_tree, train_y_tree, test_y_tree = train_test_split(data_x_tree, data_y_tree, train_size=0.9)

In [62]:
decission_model.fit(train_x_tree, train_y_tree)

DecisionTreeClassifier()

In [63]:
y_predicted = decission_model.predict(test_x_tree)

In [64]:
print(f'Score del modelo: {round(decission_model.score(test_x_tree, test_y_tree), 4) * 100}%')

Score del modelo: 50.21%


In [56]:
userRating =2
genrepreference = 3
predicted = decission_model.predict([[userRating, genrepreference]])


c:\Users\Pedro\Desktop\SemestresUni\2-2023\algoritmica\Tarea2\entornovirtual\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [57]:
print(f'La persona con {userRating} de puntuacion y con su genero de preferencia {generodepref [genrepreference]} . Se ha determinado que es {isGender[predicted[0]]}')


La persona con 2 de puntuacion y con su genero de preferencia Drama . Se ha determinado que es hombre
